name: Solar System Workflow

on:
  push:
    branches:
      - "main*"
      - "feature/*"
  workflow_dispatch:

env:
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_URI: ${{ vars.MONGO_URI }}

jobs:
  unit-testing:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Install nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.1
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Run unit tests
        if: always()
        run: npm test
      - name: Artifact the Test Results
        uses: actions/upload-artifact@v6
        with:
          name: Test results
          path: test-results.xml
  code-coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Install nodejs
        uses: actions/setup-node@v6
        with:
          node-version: 24.14.1
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Run Code Coverage
        continue-on-error: true
        run: npm run coverage
      - name: Artifact the code coverage directory
        uses: actions/upload-artifact@v6
        with:
          name: Coverage
          path: coverage
          retention-days: 5
