name: Solar System Workflow

on:
  push:
    branches:
      - "main*"
      - "feature/*"
  workflow_dispatch:

env:
  MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
  MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
  MONGO_URI: ${{ vars.MONGO_URI }}

jobs:
  # unit-testing:
  #   name: Unit Testing
  #   services:
  #     mongodb:
  #       image: mongo
  #       env:
  #         MONGO_INITDB_ROOT_USERNAME: root
  #         MONGO_INITDB_ROOT_PASSWORD: example
  #       ports:
  #         - 27017:27017
  #   runs-on: ubuntu-latest
  #   env:
  #     MONGO_USERNAME: "root"
  #     MONGO_PASSWORD: "example"
  #     MONGO_URI: "mongodb://root:example@localhost:27017"
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v6
  #     - name: Install nodejs
  #       uses: actions/setup-node@v6
  #       with:
  #         node-version: 24.14.1
  #     - name: Cache node modules
  #       id: cache-npm
  #       uses: actions/cache@v4
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Initialise seed data
  #       run: node seed.js
  #     - name: Run unit tests
  #       if: always()
  #       run: npm test
  #     - name: Artifact the Test Results
  #       uses: actions/upload-artifact@v6
  #       with:
  #         name: Test results
  #         path: test-results.xml
  # code-coverage:
  #   name: Code Coverage
  #   container:
  #     image: node:lts
  #   services:
  #     mongodb:
  #       image: mongo
  #       options: >-
  #         --name mongo
  #       env:
  #         MONGO_INITDB_ROOT_USERNAME: root
  #         MONGO_INITDB_ROOT_PASSWORD: example
  #   env:
  #     MONGO_USERNAME: "root"
  #     MONGO_PASSWORD: "example"
  #     MONGO_URI: "mongodb://root:example@mongo:27017"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repo
  #       uses: actions/checkout@v6
  #     - name: Cache node modules
  #       id: cache-npm
  #       uses: actions/cache@v4
  #       with:
  #         path: node_modules
  #         key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}
  #     - name: Install dependencies
  #       run: npm install
  #     - name: Initialise seed data
  #       run: node seed.js
  #     - name: Run Code Coverage
  #       continue-on-error: true
  #       run: npm run coverage
  #     - name: Artifact the code coverage directory
  #       uses: actions/upload-artifact@v6
  #       with:
  #         name: Coverage
  #         path: coverage
  #         retention-days: 5
  build:
    name: Docker build and push
    runs-on: ubuntu-latest
    outputs:
      k8s-image: ${{ steps.docker-image.outputs.docker-image }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build the docker image
        uses: docker/build-push-action@v7
        with:
          push: false
          context: .
          load: true
          tags: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
      - name: Test the docker build
        run: |
          docker run --rm -d --name solar-system-app \
          -p 3000:3000 \
          -e MONGO_USERNAME=${{env.MONGO_USERNAME}} \
          -e MONGO_PASSWORD=${{env.MONGO_PASSWORD}} \
          -e MONGO_URI=${{env.MONGO_URI}} \
          ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}

          echo "Testing /live endpoint"
          wget -q -O - http://127.0.0.1:3000/live | grep live
      - name: Push the docker image
        uses: docker/build-push-action@v7
        with:
          push: true
          context: .
          tags: ${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}
      - name: Output docker image
        id: docker-image
        run: echo "docker-image=${{vars.DOCKERHUB_USERNAME}}/solar-system:${{github.sha}}" >> "$GITHUB_OUTPUT"

  deploy-dev:
    name: Dev Deployment on eks
    if: contains(github.ref, 'feature/')
    needs: build
    outputs:
      app-ingress-url: ${{ steps.app-ingress-url.outputs.APP_INGRESS_URL }}
    env:
      K8S_IMAGE: ${{ needs.build.outputs.k8s-image }}
    environment:
      name: development
      url: http://${{ steps.app-ingress-url.outputs.APP_INGRESS_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Test aws setup
        run: aws configure list
      - name: Setup kubeconfig context
        run: aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.EKS_CLUSTER_NAME }}
      - name: Setup kubectl comman
        uses: azure/setup-kubectl@v4
        id: install-kubectl
      - name: Test kubectl command
        run: kubectl version
      - name: Get Ingress IP
        run: |
          INGRESS_HOSTNAME=$(kubectl get svc ingress-nginx-nginx-ingress-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "INGRESS_IP=$(nslookup $INGRESS_HOSTNAME | grep 'Address:' | grep -v '#' | tail -1 | awk '{print $2}')" >> $GITHUB_ENV
      - name: Replace placeholders in the kubernetes deployment file
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "${"
          tokenSuffix: "}"
          files: '["./kubernetes/development/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.KUBE_NAMESPACE }}
          INGRESS_IP: ${{ env.INGRESS_IP }}
          K8S_IMAGE: ${{ env.K8S_IMAGE }}
          REPLICAS: ${{ vars.REPLICAS }}
      - name: Create namespace if it doesn't exist
        run: kubectl create namespace ${{ vars.KUBE_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
      - name: Create mongo-db-creds secret
        run: |
          kubectl -n ${{ vars.KUBE_NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
            --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ env.MONGO_PASSWORD }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -
      - name: Deploy manifests
        run: kubectl apply -f kubernetes/development
      - name: Setup App Ingress Host Url
        id: app-ingress-url
        run: |
          INGRESS_URL=$(kubectl get ingress solar-system -n dev -o jsonpath='{.spec.tls[0].hosts[0]}')
          echo "APP_INGRESS_URL=$INGRESS_URL.sslip.io" >> "$GITHUB_OUTPUT"
  dev-integration-testing:
    name: Development Integration Testing
    runs-on: ubuntu-latest
    needs: deploy-dev
    env:
      APP_INGRESS_URL: ${{ needs.deploy-dev.outputs.app-ingress-url }}
    steps:
      - name: Test APP url
        run: |
          echo "Testing url: ${{ env.APP_INGRESS_URL }}"
          curl http://${{ env.APP_INGRESS_URL }}/live -s -k | jq -r .status | grep -iq live

  deploy-prod:
    name: Prod Deployment on eks
    if: github.ref == 'refs/head/main'
    needs: build
    outputs:
      app-ingress-url: ${{ steps.app-ingress-url.outputs.APP_INGRESS_URL }}
    env:
      K8S_IMAGE: ${{ needs.build.outputs.k8s-image }}
    environment:
      name: production
      url: http://${{ steps.app-ingress-url.outputs.APP_INGRESS_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Test aws setup
        run: aws configure list
      - name: Setup kubeconfig context
        run: aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ vars.EKS_CLUSTER_NAME }}
      - name: Setup kubectl comman
        uses: azure/setup-kubectl@v4
        id: install-kubectl
      - name: Test kubectl command
        run: kubectl version
      - name: Get Ingress IP
        run: |
          INGRESS_HOSTNAME=$(kubectl get svc ingress-nginx-nginx-ingress-controller -n ingress-nginx -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
          echo "INGRESS_IP=$(nslookup $INGRESS_HOSTNAME | grep 'Address:' | grep -v '#' | tail -1 | awk '{print $2}')" >> $GITHUB_ENV
      - name: Replace placeholders in the kubernetes deployment file
        uses: cschleiden/replace-tokens@v1
        with:
          tokenPrefix: "${"
          tokenSuffix: "}"
          files: '["./kubernetes/production/*.yaml"]'
        env:
          NAMESPACE: ${{ vars.KUBE_NAMESPACE }}
          INGRESS_IP: ${{ env.INGRESS_IP }}
          K8S_IMAGE: ${{ env.K8S_IMAGE }}
          REPLICAS: ${{ vars.REPLICAS }}
      - name: Create namespace if it doesn't exist
        run: kubectl create namespace ${{ vars.KUBE_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
      - name: Create mongo-db-creds secret
        run: |
          kubectl -n ${{ vars.KUBE_NAMESPACE }} create secret generic mongo-db-creds \
            --from-literal=MONGO_URI=${{ env.MONGO_URI }} \
            --from-literal=MONGO_USERNAME=${{ env.MONGO_USERNAME }} \
            --from-literal=MONGO_PASSWORD=${{ env.MONGO_PASSWORD }} \
            --save-config \
            --dry-run=client \
            -o yaml | kubectl apply -f -
      - name: Deploy manifests
        run: kubectl apply -f kubernetes/production
      - name: Setup App Ingress Host Url
        id: app-ingress-url
        run: |
          INGRESS_URL=$(kubectl get ingress solar-system -n dev -o jsonpath='{.spec.tls[0].hosts[0]}')
          echo "APP_INGRESS_URL=$INGRESS_URL.sslip.io" >> "$GITHUB_OUTPUT"
  prod-integration-testing:
    name: Production Integration Testing
    runs-on: ubuntu-latest
    needs: deploy-prod
    env:
      APP_INGRESS_URL: ${{ needs.deploy-dev.outputs.app-ingress-url }}
    steps:
      - name: Test APP url
        run: |
          echo "Testing url: ${{ env.APP_INGRESS_URL }}"
          curl http://${{ env.APP_INGRESS_URL }}/live -s -k | jq -r .status | grep -iq live
